#WAP to demonstrate basic operations on the tuple.
t=("Banana","Apple","Avocado","Kiwi","Blueberry","Cherry","Papaya","Plum")
t1=(1,5,4,3,6,2)
print(len(t))
print(t.count("B"))
print(min(t1))
print(max(t1))
print(sum(t1))
print(sorted(t1))
print(t1.index(3))
