#WAP that demonstrate the user of verious string function.
a=input("Enter a string:")
print(a.capitalize())
print(a.casefold())
print(a.count("a"))
print(a.encode())
print(a.endswith("u"))
print(a.expandtabs())
print(a.find("r"))
print(a.format())	
print(a.index("r"))	
print(a.isalnum())
print(a.isalpha())
print(a.isascii())	
print(a.isdecimal())
print(a.isdigit())	
print(a.isidentifier())	
print(a.islower())
print(a.isnumeric())	
print( a.isprintable())	
print(a.isspace())
print(a.istitle())
print(a.isupper())
print(a.join("v"))
print(a.lower())
print(a.lstrip())
print(a.rsplit())
print(a.rstrip())
print(a.split()	)
print(a.splitlines())
print(a.startswith("p"))	
print(a.strip())
print(a.swapcase())
print(a.title())
#print(a.translate())
print(a.upper())
#print(a.zfill())